#!/bin/bash
# ml_batch_rename_eer_mdoc_mrc_warp_auto.sh
#
# Renames .eer, .mdoc, and .mrc files from the Tomo5 beam-shift naming
# convention (e.g. Position_1_2) to the Warp-compatible convention
# (e.g. Position001, Position002).
#
# Usage:
#   bash ml_batch_rename_eer_mdoc_mrc_warp_auto.sh <source_dir> [<rootname>] [<start_number>]
#
# Arguments:
#   source_dir    : Directory containing .eer, .mdoc, and (optionally) .mrc files
#   rootname      : (optional) Prefix for renamed files. Default: "Position"
#   start_number  : (optional) Starting counter. Default: 0 (first output is 001)
#
# Outputs:
#   - Renames files in-place
#   - Writes listfile_<rootname>.txt: two-column mapping of old_name -> new_name
#     This file is REQUIRED later for translating user exclusion tables that
#     reference original position names (e.g. Position_1_2) into the renamed
#     form (Position005) used by downstream scripts.
#   - Fixes mdoc date format for current and previous years (yy-mmm-dd required by Warp)
#
# Integration with warp_auto.py:
#   - The listfile is written as listfile_<rootname>.txt in the source dir
#   - Also written (symlinked) as listfile.txt for consistent parsing
#   - warp_auto.py's prepare_tilts step reads this file to map
#     user-provided exclusion tables (in old naming) to renamed form

set -e

# -----------------------------------------------------------------------------
# Argument handling
# -----------------------------------------------------------------------------

if [ -z "$1" ]; then
    cat <<EOF
Usage: bash $0 <source_dir> [<rootname>] [<start_number>]

Example:
    bash $0 /ceph/users/me/data/grid9_raw Position 0

Arguments:
    source_dir    Directory containing .eer + .mdoc + .mrc files to rename
    rootname      Prefix (default: Position)
    start_number  Starting counter, 0 = first output is 001 (default: 0)
EOF
    exit 1
fi

SOURCE_DIR="$1"
ROOTNAME="${2:-Position}"
START_NUM="${3:-0}"

if [ ! -d "$SOURCE_DIR" ]; then
    echo "ERROR: Directory not found: $SOURCE_DIR"
    exit 1
fi

cd "$SOURCE_DIR" || { echo "ERROR: Cannot cd to $SOURCE_DIR"; exit 1; }

LISTFILE="listfile_${ROOTNAME}.txt"
LISTFILE_GENERIC="listfile.txt"

echo "========================================"
echo "ml_batch_rename_eer_mdoc_mrc_warp_auto"
echo "Directory: $SOURCE_DIR"
echo "Rootname:  $ROOTNAME"
echo "Start num: $START_NUM"
echo "Listfile:  $LISTFILE"
echo "Started:   $(date)"
echo "========================================"

# -----------------------------------------------------------------------------
# Validate there's something to rename
# -----------------------------------------------------------------------------

shopt -s nullglob
mdocs=( *.mdoc )
if [ ${#mdocs[@]} -eq 0 ]; then
    echo "ERROR: No .mdoc files found in $SOURCE_DIR"
    exit 1
fi

# Detect if files are already renamed (starting with Position followed by 3 digits)
already_renamed=0
for m in "${mdocs[@]}"; do
    if [[ "$m" =~ ^${ROOTNAME}[0-9]{3}\.mdoc$ ]]; then
        already_renamed=$((already_renamed + 1))
    fi
done
if [ "$already_renamed" -gt 0 ] && [ "$already_renamed" -eq "${#mdocs[@]}" ]; then
    echo "WARNING: All ${#mdocs[@]} mdoc files appear to already be in renamed form"
    echo "         (${ROOTNAME}NNN.mdoc). Nothing to do. If you need to force rerun,"
    echo "         remove these files or run in a different directory."
    exit 0
fi

# -----------------------------------------------------------------------------
# Initialize mapping file
# -----------------------------------------------------------------------------

# Write header comment to listfile
cat > "$LISTFILE" <<EOF
# File name mapping generated by ml_batch_rename_eer_mdoc_mrc_warp_auto.sh
# Generated: $(date)
# Source directory: $SOURCE_DIR
#
# Format: <original_position_name> <renamed_position_name>
# Use this file to translate user-provided exclusion tables (which reference
# the original names) into the renamed form used by downstream processing.
EOF

# -----------------------------------------------------------------------------
# Main rename loop
# -----------------------------------------------------------------------------

numb=$START_NUM
renamed_count=0
skipped_count=0

for mdoc in *.mdoc; do
    # Skip files that look already-renamed
    if [[ "$mdoc" =~ ^${ROOTNAME}[0-9]{3}\.mdoc$ ]]; then
        continue
    fi

    numb=$((10#$numb + 1))
    newnum=$(printf "%03d" "$numb")
    iname="${mdoc%.mdoc}"
    newname="${ROOTNAME}${newnum}"

    echo "$iname $newname" >> "$LISTFILE"

    # Rename .eer files matching this position
    eer_count=0
    for eer in "$iname"_[0-9][0-9][0-9]*_EER.eer; do
        [ -e "$eer" ] || continue
        suffix="${eer#$iname}"   # e.g. _013_21.00_20260331_EER.eer
        new_eer="${newname}${suffix}"
        mv "$eer" "$new_eer"
        eer_count=$((eer_count + 1))
    done

    # Rewrite references inside the mdoc, then rename the mdoc itself
    if [ -f "$mdoc" ]; then
        sed -i "s/${iname}/${newname}/g" "$mdoc"
        mv "$mdoc" "${newname}.mdoc"
    fi

    # Rename combined .mrc stack if present
    if [ -f "${iname}.mrc" ]; then
        mv "${iname}.mrc" "${newname}.mrc"
    fi

    echo "  $iname -> $newname ($eer_count .eer files)"
    renamed_count=$((renamed_count + 1))
done

# -----------------------------------------------------------------------------
# Fix mdoc date formatting (Warp requires yy-mmm-dd)
# -----------------------------------------------------------------------------

echo ""
echo "Fixing mdoc date format..."

# Shorten the 4-digit year to 2 digits (matches current year and year before)
current_year=$(date +%Y)
prev_year=$((current_year - 1))

for year in "$current_year" "$prev_year"; do
    short="${year: -2}"
    sed -i "s/-${year}/-${short}/g" *.mdoc 2>/dev/null || true
done

# Swap day and year: dd-mmm-yy -> yy-mmm-dd
sed -i -E 's/([0-9]{2})-([A-Z][a-z]{2})-([0-9]{2})/\3-\2-\1/g' *.mdoc

echo "Date format fixed."

# -----------------------------------------------------------------------------
# Create generic listfile symlink for warp_auto.py
# -----------------------------------------------------------------------------

ln -sf "$LISTFILE" "$LISTFILE_GENERIC"

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------

echo ""
echo "========================================"
echo "Summary:"
echo "  Positions renamed:   $renamed_count"
echo "  Skipped (already renamed or no match): $skipped_count"
echo "  Mapping file:        $LISTFILE"
echo "  Generic symlink:     $LISTFILE_GENERIC"
echo "Finished: $(date)"
echo "========================================"

exit 0
